language: android
jdk: oraclejdk7
env:
  android:
    components:
      - build-tools-19.1.0
      - android-19
      - sysimg-19
      - extra-android-support
    licenses:
      - android-sdk-license-5be876d5
      - '.*intel.+'
    before_install:
      - android list sdk --no-ui --all --extended

script:
  - chmod +x gradlew
  - ./gradlew assemble connectedCheck
